### ISSUE TITLE
Elevator Mod call button

### ISSUE THREAD

**Issue by AussiePilot123** [Thuts-Mods/ThutTech#1]
#### Issue Description:	
When I select call button in the settings, the graphics seem to be broken.

#### What happens:	
The call button works, but it dosen't display the numbers properly.
![2020-05-15_09 44 57](https://user-images.githubusercontent.com/65369842/81996936-c05d8480-9691-11ea-83eb-4f201853d3bf.png)

#### What you expected to happen:	
I thought it would look like the video's i've seen.

#### Steps to reproduce:	

1. Set up elevator	
2. Go into control block settings
3. Set it to call button and exit.
...	

____	
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.	

- Thutcore: thutcore-1.15.2-7.2.0	
- Minecraft: 1.15.2
- Forge: 1.15.2 - 31.1.88

**Comment by Thutmose** [comment]
the next update will fix this issue

**Comment by AussiePilot123** [comment]
Thank you
