### ISSUE TITLE
Redstone calling

### ISSUE THREAD

**Issue by hartontw** [Thuts-Mods/ThutTech#16]
I am aware about the redstone signal comes from controller block when elevator is on the floor. (Output)

My suggestion is adding some way to call the elevator through a redstone signal. (Input)

Nice mod BTW. Thank you.

**Comment by Thutmose** [comment]
that should work if you apply a strong redstone signal to a call panel.

place a redstone repeater facing a face of a controller set to a call panel, then give it a signal, it should call it to that floor

**Comment by hartontw** [comment]
I've tried that, maybe is the version:

Minecraft 1.12.2
Forge 14.23.5.2854
Thut Core 1.12.2-5.21.0
Thut's Elevators 1.12.2-6.1.6

[Approaches](https://ibb.co/CwZ2ry4)

**Comment by Thutmose** [comment]
See if it works in 1.16.4-9.1.0, version 6.1.6 is something like a year and a half out of date

**Comment by hartontw** [comment]
I see. I'm playing in 1.12.2 right now but I already know for future servers.
