### ISSUE TITLE
Cant setup elevators [1.7.10]

### ISSUE THREAD

**Issue by AstroDaFloof** [Thuts-Mods/ThutTech#25]
#### Issue Description:	
I can't setup elevators.
I right click the elevator block with the linking device and then shift + right click the other elevator block but nothing happens

#### What happens:	
Nothing happens

#### What you expected to happen:	
Normaly ecpected a chat messaged that should say "Linked *coordinates* to *coordinates*" or "Elevator created" or some stuff 
along those lines

#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.	

- Thutcore: 	
- Minecraft: 1.7.10
- Forge:

**Comment by spannerman79** [comment]
Related issue - https://github.com/Thuts-Mods/ThutTech/issues/28

**Comment by Thutmose** [comment]
1.7.10 used a completely different way to make the elevators, you may need to dig through the old minecraft forums to see if you can find instructions, as 1.7.10 support ended many years ago.
