### ISSUE TITLE
No Thutcore for 1.7.10

### ISSUE THREAD

**Issue by spannerman79** [Thuts-Mods/ThutTech#28]
Affected Mods: https://www.curseforge.com/minecraft/mc-mods/thuts-elevators/files/all?filter-game-version=2020709689%3A4449

Thutcore listing for 1.7.10 - https://www.curseforge.com/minecraft/mc-mods/thutcore/files/all?filter-game-version=2020709689%3A4449

**Comment by Thutmose** [comment]
the final 1.7.10 version included thutcore in the jar, that being said, 1.7.10 supported ended over half a decade ago.

**Comment by spannerman79** [comment]
You may want to update the dependency listing on https://www.curseforge.com/minecraft/mc-mods/thuts-elevators/files/2268219 then.

**That** was the reason why I opened this issue in the first place.

_NB: I am not asking for direct bug issue support and expecting bugs with the final 1.7.10 mod to be resolved_
