### ISSUE TITLE
Unintentional behaviour with redstone ++

### ISSUE THREAD

**Issue by Multi-Coder-24** [Thuts-Mods/ThutTech#5]
When you have installed redstone ++ and you can push tile entity's. The elevator can be pushed by a block and a piston.	

1. Create a elevator.
2. Place stone next to elevator.
3. Place piston behind stone.
4. Send 1 redstone tick pulse into piston.
5. Elevator moves.

I expected the piston not to push the block or elevator.

I am using phone my computer is not working until later so I will add missing information.

- Thutcore: will add later
- ThutTech: will add later.
- Minecraft: 1.12.2
- Forge: (2854)

**Comment by Thutmose** [comment]
this probably also happens with vanilla pistons, ie without the Redstone++ mod?

elevators are entities, and those can be pushed by pistons

**Comment by Multi-Coder-24** [comment]
ok no problem that answers that one then
